# Tutorial clasificador MIMLBRkNN

In [32]:
import sys
from pathlib import Path

sys.path.insert(
    0,
    str(Path.home() / "GitHub" / "MIML" / "src")
)
output_path = str(Path.home() / "GitHub" / "MIML" / "src" / "miml" / "tutorial")

from miml.data import load_dataset

import miml

print(miml.__file__)

/home/juanjo/GitHub/MIML/src/miml/__init__.py

# Install dependencies

In [33]:
%pip install numpy pandas scikit-learn matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /home/juanjo/.local/lib/python3.10/site-packages (2.2.6)
Requirement already satisfied: pandas in /home/juanjo/.local/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: scikit-learn in /home/juanjo/.local/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: matplotlib in /home/juanjo/.local/lib/python3.10/site-packages (3.10.9)
Requirement already satisfied: seaborn in /home/juanjo/.local/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: tzdata>=2022.7 in /home/juanjo/.local/lib/python3.10/site-packages (from pandas) (2026.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/juanjo/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.8.0 in /home/juanjo/.local/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/juanjo/.local/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: joblib>=1.2.0 in /home/juanjo/.local/lib/python3.10/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: cycler>=0.10 in /home/juanjo/.local/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: packaging>=20.0 in /home/juanjo/.local/lib/python3.10/site-packages (from matplotlib) (26.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/juanjo/.local/lib/python3.10/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in /home/juanjo/.local/lib/python3.10/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/juanjo/.local/lib/python3.10/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/juanjo/.local/lib/python3.10/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: pyparsing>=3 in /home/juanjo/.local/lib/python3.10/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /home/juanjo/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

# Import metrics, classifier and Hausdorff distances

In [34]:
import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    hamming_loss,
)

# Add the project source directory to Python's path.
sys.path.insert(
    0,
    str(Path.home() / "GitHub" / "MIML" / "src"),
)

from miml.data import load_dataset
from miml.report import Report

from miml.classifier.miml.lazy.miml_dgc import MIMLDGC

from miml.core.average_hausdorff import AverageHausdorff
from miml.core.maximal_hausdorff import MaximalHausdorff
from miml.core.minimal_hausdorff import MinimalHausdorff

# Load datasets

In [35]:
birds = load_dataset(
    "miml_birds.arff",
    from_library=True,
)

birds_train, birds_test = birds.split_dataset(
    train_percentage=0.8,
    seed=7,
)

# Run algorithm and save results in table

In [36]:
classifier = MIMLDGC(metric=AverageHausdorff(), num_of_neighbours=10)
classifier.build(birds_train) 

average_distances = pd.DataFrame(classifier.D)

average_distances

,0,1,2,3,4,5,6,7,8,9,...,196,197,198,199,200,201,202,203,204,205
0,0.000000,0.995976,0.996368,0.996911,0.999311,0.998720,0.997003,0.998559,0.998242,0.998446,...,0.997906,0.996343,0.997810,0.998579,0.997815,0.997705,0.994747,0.998607,0.995809,0.997153
1,0.995976,0.000000,0.996636,0.997592,0.999397,0.999004,0.998089,0.998462,0.998685,0.998561,...,0.997621,0.996830,0.997613,0.998833,0.993577,0.997498,0.995970,0.998817,0.995039,0.997709
2,0.996368,0.996636,0.000000,0.996427,0.999018,0.997995,0.992913,0.997786,0.997534,0.997760,...,0.997023,0.992634,0.996780,0.998172,0.997302,0.995947,0.994797,0.998050,0.996846,0.995855
3,0.996911,0.997592,0.996427,0.000000,0.998196,0.997732,0.996636,0.998181,0.997899,0.998020,...,0.997150,0.996683,0.994267,0.998043,0.998327,0.997462,0.994812,0.998321,0.997673,0.996532
4,0.999311,0.999397,0.999018,0.998196,0.000000,0.998631,0.998844,0.999524,0.999202,0.999389,...,0.999340,0.999009,0.998510,0.999070,0.999466,0.999369,0.998965,0.999412,0.999426,0.999029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,0.997705,0.997498,0.995947,0.997462,0.999369,0.998125,0.996308,0.996245,0.994682,0.994986,...,0.993793,0.990910,0.997270,0.998631,0.997717,0.000000,0.996469,0.995268,0.996159,0.992701
202,0.994747,0.995970,0.994797,0.994812,0.998965,0.998452,0.996453,0.997841,0.997843,0.997876,...,0.996479,0.994479,0.996411,0.997461,0.997553,0.996469,0.000000,0.998244,0.996388,0.996194
203,0.998607,0.998817,0.998050,0.998321,0.999412,0.997824,0.997021,0.991735,0.986173,0.986326,...,0.995529,0.996306,0.998529,0.998831,0.998930,0.995268,0.998244,0.000000,0.998138,0.994096
204,0.995809,0.995039,0.996846,0.997673,0.999426,0.998739,0.997603,0.997463,0.997959,0.997662,...,0.996864,0.995262,0.997847,0.998878,0.996725,0.996159,0.996388,0.998138,0.000000,0.996240
205,0.997153,0.997709,0.995855,0.996532,0.999029,0.997313,0.994447,0.992638,0.992409,0.992158,...,0.992927,0.992390,0.996914,0.998109,0.998369,0.992701,0.996194,0.994096,0.996240,0.000000

In [37]:

classifier = MIMLDGC(metric=MinimalHausdorff(), num_of_neighbours=10)
classifier.build(birds_train) 
minimal_distances = pd.DataFrame(classifier.D)

minimal_distances

,0,1,2,3,4,5,6,7,8,9,...,196,197,198,199,200,201,202,203,204,205
0,0.000000,111.066916,86.375733,91.791317,204.129057,72.581056,91.977977,153.726814,47.901484,112.999201,...,205.121852,48.254057,55.307432,58.912534,250.650292,46.618723,79.549615,86.482286,80.013391,47.824562
1,111.066916,0.000000,84.840776,93.734636,621.036348,525.485657,81.915489,230.453888,454.115507,335.926718,...,180.467910,77.827012,113.658480,128.082201,53.788839,176.404536,51.004466,522.110414,135.329458,71.118258
2,86.375733,84.840776,0.000000,43.284488,206.901876,94.628597,41.020661,103.717117,55.686604,100.703281,...,196.669790,20.657133,66.083767,17.201652,71.390197,34.442552,23.016584,67.779851,122.425100,74.101346
3,91.791317,93.734636,43.284488,0.000000,41.575960,81.896786,73.439184,77.529307,53.897822,64.207737,...,28.513081,101.334792,68.025707,16.711571,101.034552,80.166664,23.398544,71.856759,33.745576,10.058223
4,204.129057,621.036348,206.901876,41.575960,0.000000,114.846061,121.227506,121.259798,39.813280,101.411878,...,56.243820,221.157288,188.797889,65.072889,924.194427,229.007094,35.012693,123.256781,457.772105,75.999185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,46.618723,176.404536,34.442552,80.166664,229.007094,95.867102,42.629361,210.245984,50.522701,119.602018,...,121.628527,36.245446,49.284471,24.200066,160.628330,0.000000,40.225231,104.590591,193.975300,34.608101
202,79.549615,51.004466,23.016584,23.398544,35.012693,78.832398,54.356225,91.517794,34.648416,65.362858,...,14.792173,13.332770,26.893963,21.660706,10.445485,40.225231,0.000000,69.689819,102.320916,43.218206
203,86.482286,522.110414,67.779851,71.856759,123.256781,11.057956,33.171727,48.120735,45.859255,21.979694,...,118.151268,87.845228,59.542533,67.098903,826.439112,104.590591,69.689819,0.000000,346.593523,14.807957
204,80.013391,135.329458,122.425100,33.745576,457.772105,347.321472,115.952268,189.552423,274.504328,228.826344,...,225.355339,48.277584,100.835800,146.333236,215.324643,193.975300,102.320916,346.593523,0.000000,39.867466
205,47.824562,71.118258,74.101346,10.058223,75.999185,23.221262,24.435099,46.822216,16.069980,32.653476,...,33.896724,63.999475,28.701955,30.500715,316.825665,34.608101,43.218206,14.807957,39.867466,0.000000

In [38]:

classifier = MIMLDGC(metric=MaximalHausdorff(), num_of_neighbours=10)
classifier.build(birds_train) 
maximal_distances = pd.DataFrame(classifier.D)

maximal_distances

,0,1,2,3,4,5,6,7,8,9,...,196,197,198,199,200,201,202,203,204,205
0,0.000000,505.758085,522.590227,499.944108,1799.068783,1357.975785,755.554949,1561.591221,1834.007007,1685.718995,...,1146.009332,1115.383996,945.003313,882.487670,837.125767,1195.645069,283.649912,1899.564130,663.424420,1347.506210
1,505.758085,0.000000,610.340500,283.874782,1555.266159,1470.821261,888.472741,1133.780893,1399.554976,1252.320312,...,722.617674,680.283626,522.037313,450.730819,398.626106,771.890492,110.582061,1465.092343,348.051365,921.194571
2,522.590227,610.340500,0.000000,833.125203,1317.944967,876.613037,302.004496,1894.640011,2163.475926,2018.315081,...,1479.464356,1443.907007,1277.638850,1213.330271,1162.875538,1526.259591,599.027603,2230.181786,991.233487,1680.351248
3,499.944108,283.874782,833.125203,0.000000,1492.437582,1410.079587,1284.682913,3287.439781,3559.366408,3408.281989,...,2870.451124,2838.692687,447.823500,2605.651500,2555.614016,2925.883905,1987.568157,3625.046085,2394.440505,3074.380642
4,1799.068783,1555.266159,1317.944967,1492.437582,0.000000,2586.427711,3268.532644,5262.546094,5539.156997,5380.721221,...,4845.041747,4821.024111,1716.322930,2841.540446,4538.033584,4908.355615,3973.023312,5601.916237,4380.325368,5050.564680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,1195.645069,771.890492,1526.259591,2925.883905,4908.355615,2358.828515,1645.573785,254.041913,259.533074,190.765143,...,255.218923,291.673596,3234.326766,7722.617038,386.469053,0.000000,123.272903,706.965786,271.878647,181.244237
202,283.649912,110.582061,599.027603,1987.568157,3973.023312,1434.607484,718.404602,240.237627,72.394060,191.955320,...,194.368352,166.028233,2301.738299,6784.570587,77.076316,123.272903,0.000000,1639.931701,495.502938,1096.695432
203,1899.564130,1465.092343,2230.181786,3625.046085,5601.916237,3062.757958,2346.838374,358.121777,141.116932,241.624159,...,767.173372,790.155422,3935.410595,8419.186502,1073.322210,706.965786,1639.931701,0.000000,430.581785,57.148485
204,663.424420,348.051365,991.233487,2394.440505,4380.325368,1826.684402,1116.401134,477.182869,489.694687,454.284647,...,499.550016,371.947781,2703.958633,7191.563199,334.159193,271.878647,495.502938,430.581785,0.000000,699.217492
205,1347.506210,921.194571,1680.351248,3074.380642,5050.564680,2507.792170,1792.873002,80.949807,76.417965,131.512206,...,207.057330,279.614338,3381.063392,7867.689534,545.298089,181.244237,1096.695432,57.148485,699.217492,0.000000